// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/vitaledge/v1/ddl.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVertexPropertyIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Property      string                 `protobuf:"bytes,3,opt,name=property,proto3" json:"property,omitempty"`
	IfNotExists   bool                   `protobuf:"varint,4,opt,name=if_not_exists,json=ifNotExists,proto3" json:"if_not_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVertexPropertyIndexRequest) Reset() {
	*x = CreateVertexPropertyIndexRequest{}
	mi := &file_api_proto_vitaledge_v1_ddl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVertexPropertyIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVertexPropertyIndexRequest) ProtoMessage() {}

func (x *CreateVertexPropertyIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_ddl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVertexPropertyIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateVertexPropertyIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_ddl_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVertexPropertyIndexRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CreateVertexPropertyIndexRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *CreateVertexPropertyIndexRequest) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *CreateVertexPropertyIndexRequest) GetIfNotExists() bool {
	if x != nil {
		return x.IfNotExists
	}
	return false
}

type CreateVertexPropertyIndexResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Created         bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	IndexedEntities int64                  `protobuf:"varint,2,opt,name=indexed_entities,json=indexedEntities,proto3" json:"indexed_entities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateVertexPropertyIndexResponse) Reset() {
	*x = CreateVertexPropertyIndexResponse{}
	mi := &file_api_proto_vitaledge_v1_ddl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVertexPropertyIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVertexPropertyIndexResponse) ProtoMessage() {}

func (x *CreateVertexPropertyIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_ddl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVertexPropertyIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateVertexPropertyIndexResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_ddl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVertexPropertyIndexResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *CreateVertexPropertyIndexResponse) GetIndexedEntities() int64 {
	if x != nil {
		return x.IndexedEntities
	}
	return 0
}

type CreateEdgePropertyIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Property      string                 `protobuf:"bytes,3,opt,name=property,proto3" json:"property,omitempty"`
	IfNotExists   bool                   `protobuf:"varint,4,opt,name=if_not_exists,json=ifNotExists,proto3" json:"if_not_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgePropertyIndexRequest) Reset() {
	*x = CreateEdgePropertyIndexRequest{}
	mi := &file_api_proto_vitaledge_v1_ddl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgePropertyIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgePropertyIndexRequest) ProtoMessage() {}

func (x *CreateEdgePropertyIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_ddl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgePropertyIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateEdgePropertyIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_ddl_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEdgePropertyIndexRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CreateEdgePropertyIndexRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *CreateEdgePropertyIndexRequest) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *CreateEdgePropertyIndexRequest) GetIfNotExists() bool {
	if x != nil {
		return x.IfNotExists
	}
	return false
}

type CreateEdgePropertyIndexResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Created         bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	IndexedEntities int64                  `protobuf:"varint,2,opt,name=indexed_entities,json=indexedEntities,proto3" json:"indexed_entities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateEdgePropertyIndexResponse) Reset() {
	*x = CreateEdgePropertyIndexResponse{}
	mi := &file_api_proto_vitaledge_v1_ddl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgePropertyIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgePropertyIndexResponse) ProtoMessage() {}

func (x *CreateEdgePropertyIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_ddl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgePropertyIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateEdgePropertyIndexResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_ddl_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEdgePropertyIndexResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *CreateEdgePropertyIndexResponse) GetIndexedEntities() int64 {
	if x != nil {
		return x.IndexedEntities
	}
	return 0
}

var File_api_proto_vitaledge_v1_ddl_proto protoreflect.FileDescriptor

const file_api_proto_vitaledge_v1_ddl_proto_rawDesc = "" +
	"\n" +
	" api/proto/vitaledge/v1/ddl.proto\x12\fvitaledge.v1\"\x92\x01\n" +
	" CreateVertexPropertyIndexRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x1a\n" +
	"\bproperty\x18\x03 \x01(\tR\bproperty\x12\"\n" +
	"\rif_not_exists\x18\x04 \x01(\bR\vifNotExists\"h\n" +
	"!CreateVertexPropertyIndexResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12)\n" +
	"\x10indexed_entities\x18\x02 \x01(\x03R\x0findexedEntities\"\x90\x01\n" +
	"\x1eCreateEdgePropertyIndexRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x1a\n" +
	"\bproperty\x18\x03 \x01(\tR\bproperty\x12\"\n" +
	"\rif_not_exists\x18\x04 \x01(\bR\vifNotExists\"f\n" +
	"\x1fCreateEdgePropertyIndexResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12)\n" +
	"\x10indexed_entities\x18\x02 \x01(\x03R\x0findexedEntities2\x82\x02\n" +
	"\n" +
	"DdlService\x12|\n" +
	"\x19CreateVertexPropertyIndex\x12..vitaledge.v1.CreateVertexPropertyIndexRequest\x1a/.vitaledge.v1.CreateVertexPropertyIndexResponse\x12v\n" +
	"\x17CreateEdgePropertyIndex\x12,.vitaledge.v1.CreateEdgePropertyIndexRequest\x1a-.vitaledge.v1.CreateEdgePropertyIndexResponseB;Z9github.com/spaceqraft/vitaledge/api/proto/vitaledge/v1;v1b\x06proto3"

var (
	file_api_proto_vitaledge_v1_ddl_proto_rawDescOnce sync.Once
	file_api_proto_vitaledge_v1_ddl_proto_rawDescData []byte
)

func file_api_proto_vitaledge_v1_ddl_proto_rawDescGZIP() []byte {
	file_api_proto_vitaledge_v1_ddl_proto_rawDescOnce.Do(func() {
		file_api_proto_vitaledge_v1_ddl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_vitaledge_v1_ddl_proto_rawDesc), len(file_api_proto_vitaledge_v1_ddl_proto_rawDesc)))
	})
	return file_api_proto_vitaledge_v1_ddl_proto_rawDescData
}

var file_api_proto_vitaledge_v1_ddl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_vitaledge_v1_ddl_proto_goTypes = []any{
	(*CreateVertexPropertyIndexRequest)(nil),  // 0: vitaledge.v1.CreateVertexPropertyIndexRequest
	(*CreateVertexPropertyIndexResponse)(nil), // 1: vitaledge.v1.CreateVertexPropertyIndexResponse
	(*CreateEdgePropertyIndexRequest)(nil),    // 2: vitaledge.v1.CreateEdgePropertyIndexRequest
	(*CreateEdgePropertyIndexResponse)(nil),   // 3: vitaledge.v1.CreateEdgePropertyIndexResponse
}
var file_api_proto_vitaledge_v1_ddl_proto_depIdxs = []int32{
	0, // 0: vitaledge.v1.DdlService.CreateVertexPropertyIndex:input_type -> vitaledge.v1.CreateVertexPropertyIndexRequest
	2, // 1: vitaledge.v1.DdlService.CreateEdgePropertyIndex:input_type -> vitaledge.v1.CreateEdgePropertyIndexRequest
	1, // 2: vitaledge.v1.DdlService.CreateVertexPropertyIndex:output_type -> vitaledge.v1.CreateVertexPropertyIndexResponse
	3, // 3: vitaledge.v1.DdlService.CreateEdgePropertyIndex:output_type -> vitaledge.v1.CreateEdgePropertyIndexResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_vitaledge_v1_ddl_proto_init() }
func file_api_proto_vitaledge_v1_ddl_proto_init() {
	if File_api_proto_vitaledge_v1_ddl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_vitaledge_v1_ddl_proto_rawDesc), len(file_api_proto_vitaledge_v1_ddl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_vitaledge_v1_ddl_proto_goTypes,
		DependencyIndexes: file_api_proto_vitaledge_v1_ddl_proto_depIdxs,
		MessageInfos:      file_api_proto_vitaledge_v1_ddl_proto_msgTypes,
	}.Build()
	File_api_proto_vitaledge_v1_ddl_proto = out.File
	file_api_proto_vitaledge_v1_ddl_proto_goTypes = nil
	file_api_proto_vitaledge_v1_ddl_proto_depIdxs = nil
}
