// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/vitaledge/v1/ddl.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DdlService_CreateVertexPropertyIndex_FullMethodName = "/vitaledge.v1.DdlService/CreateVertexPropertyIndex"
	DdlService_CreateEdgePropertyIndex_FullMethodName   = "/vitaledge.v1.DdlService/CreateEdgePropertyIndex"
)

// DdlServiceClient is the client API for DdlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DdlServiceClient interface {
	CreateVertexPropertyIndex(ctx context.Context, in *CreateVertexPropertyIndexRequest, opts ...grpc.CallOption) (*CreateVertexPropertyIndexResponse, error)
	CreateEdgePropertyIndex(ctx context.Context, in *CreateEdgePropertyIndexRequest, opts ...grpc.CallOption) (*CreateEdgePropertyIndexResponse, error)
}

type ddlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDdlServiceClient(cc grpc.ClientConnInterface) DdlServiceClient {
	return &ddlServiceClient{cc}
}

func (c *ddlServiceClient) CreateVertexPropertyIndex(ctx context.Context, in *CreateVertexPropertyIndexRequest, opts ...grpc.CallOption) (*CreateVertexPropertyIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVertexPropertyIndexResponse)
	err := c.cc.Invoke(ctx, DdlService_CreateVertexPropertyIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ddlServiceClient) CreateEdgePropertyIndex(ctx context.Context, in *CreateEdgePropertyIndexRequest, opts ...grpc.CallOption) (*CreateEdgePropertyIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEdgePropertyIndexResponse)
	err := c.cc.Invoke(ctx, DdlService_CreateEdgePropertyIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DdlServiceServer is the server API for DdlService service.
// All implementations must embed UnimplementedDdlServiceServer
// for forward compatibility.
type DdlServiceServer interface {
	CreateVertexPropertyIndex(context.Context, *CreateVertexPropertyIndexRequest) (*CreateVertexPropertyIndexResponse, error)
	CreateEdgePropertyIndex(context.Context, *CreateEdgePropertyIndexRequest) (*CreateEdgePropertyIndexResponse, error)
	mustEmbedUnimplementedDdlServiceServer()
}

// UnimplementedDdlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDdlServiceServer struct{}

func (UnimplementedDdlServiceServer) CreateVertexPropertyIndex(context.Context, *CreateVertexPropertyIndexRequest) (*CreateVertexPropertyIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVertexPropertyIndex not implemented")
}
func (UnimplementedDdlServiceServer) CreateEdgePropertyIndex(context.Context, *CreateEdgePropertyIndexRequest) (*CreateEdgePropertyIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEdgePropertyIndex not implemented")
}
func (UnimplementedDdlServiceServer) mustEmbedUnimplementedDdlServiceServer() {}
func (UnimplementedDdlServiceServer) testEmbeddedByValue()                    {}

// UnsafeDdlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DdlServiceServer will
// result in compilation errors.
type UnsafeDdlServiceServer interface {
	mustEmbedUnimplementedDdlServiceServer()
}

func RegisterDdlServiceServer(s grpc.ServiceRegistrar, srv DdlServiceServer) {
	// If the following call panics, it indicates UnimplementedDdlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DdlService_ServiceDesc, srv)
}

func _DdlService_CreateVertexPropertyIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVertexPropertyIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdlServiceServer).CreateVertexPropertyIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DdlService_CreateVertexPropertyIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdlServiceServer).CreateVertexPropertyIndex(ctx, req.(*CreateVertexPropertyIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DdlService_CreateEdgePropertyIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEdgePropertyIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdlServiceServer).CreateEdgePropertyIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DdlService_CreateEdgePropertyIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdlServiceServer).CreateEdgePropertyIndex(ctx, req.(*CreateEdgePropertyIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DdlService_ServiceDesc is the grpc.ServiceDesc for DdlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DdlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vitaledge.v1.DdlService",
	HandlerType: (*DdlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVertexPropertyIndex",
			Handler:    _DdlService_CreateVertexPropertyIndex_Handler,
		},
		{
			MethodName: "CreateEdgePropertyIndex",
			Handler:    _DdlService_CreateEdgePropertyIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/vitaledge/v1/ddl.proto",
}
