// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/vitaledge/v1/dml.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Input         *QueryInput            `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Options       *RequestOptions        `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	Client        *ClientContext         `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	Parameters    map[string]*Value      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *QueryRequest) GetInput() *QueryInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *QueryRequest) GetOptions() *RequestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QueryRequest) GetClient() *ClientContext {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *QueryRequest) GetParameters() map[string]*Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type QueryInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*QueryInput_Cypher
	//	*QueryInput_Prepared
	Kind          isQueryInput_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryInput) Reset() {
	*x = QueryInput{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInput) ProtoMessage() {}

func (x *QueryInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInput.ProtoReflect.Descriptor instead.
func (*QueryInput) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{1}
}

func (x *QueryInput) GetKind() isQueryInput_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *QueryInput) GetCypher() string {
	if x != nil {
		if x, ok := x.Kind.(*QueryInput_Cypher); ok {
			return x.Cypher
		}
	}
	return ""
}

func (x *QueryInput) GetPrepared() *PreparedQuery {
	if x != nil {
		if x, ok := x.Kind.(*QueryInput_Prepared); ok {
			return x.Prepared
		}
	}
	return nil
}

type isQueryInput_Kind interface {
	isQueryInput_Kind()
}

type QueryInput_Cypher struct {
	Cypher string `protobuf:"bytes,1,opt,name=cypher,proto3,oneof"`
}

type QueryInput_Prepared struct {
	Prepared *PreparedQuery `protobuf:"bytes,2,opt,name=prepared,proto3,oneof"`
}

func (*QueryInput_Cypher) isQueryInput_Kind() {}

func (*QueryInput_Prepared) isQueryInput_Kind() {}

type PreparedQuery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ParserVersion  string                 `protobuf:"bytes,1,opt,name=parser_version,json=parserVersion,proto3" json:"parser_version,omitempty"`
	IrVersion      string                 `protobuf:"bytes,2,opt,name=ir_version,json=irVersion,proto3" json:"ir_version,omitempty"`
	Fingerprint    string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Payload        []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	FallbackCypher string                 `protobuf:"bytes,5,opt,name=fallback_cypher,json=fallbackCypher,proto3" json:"fallback_cypher,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreparedQuery) Reset() {
	*x = PreparedQuery{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedQuery) ProtoMessage() {}

func (x *PreparedQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedQuery.ProtoReflect.Descriptor instead.
func (*PreparedQuery) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{2}
}

func (x *PreparedQuery) GetParserVersion() string {
	if x != nil {
		return x.ParserVersion
	}
	return ""
}

func (x *PreparedQuery) GetIrVersion() string {
	if x != nil {
		return x.IrVersion
	}
	return ""
}

func (x *PreparedQuery) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *PreparedQuery) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PreparedQuery) GetFallbackCypher() string {
	if x != nil {
		return x.FallbackCypher
	}
	return ""
}

type RequestOptions struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReadOnly              bool                   `protobuf:"varint,1,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	IncludeStats          bool                   `protobuf:"varint,2,opt,name=include_stats,json=includeStats,proto3" json:"include_stats,omitempty"`
	IncludeWarnings       bool                   `protobuf:"varint,3,opt,name=include_warnings,json=includeWarnings,proto3" json:"include_warnings,omitempty"`
	AllowFallbackToCypher bool                   `protobuf:"varint,4,opt,name=allow_fallback_to_cypher,json=allowFallbackToCypher,proto3" json:"allow_fallback_to_cypher,omitempty"`
	StrictVariantDispatch bool                   `protobuf:"varint,5,opt,name=strict_variant_dispatch,json=strictVariantDispatch,proto3" json:"strict_variant_dispatch,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RequestOptions) Reset() {
	*x = RequestOptions{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOptions) ProtoMessage() {}

func (x *RequestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOptions.ProtoReflect.Descriptor instead.
func (*RequestOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{3}
}

func (x *RequestOptions) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *RequestOptions) GetIncludeStats() bool {
	if x != nil {
		return x.IncludeStats
	}
	return false
}

func (x *RequestOptions) GetIncludeWarnings() bool {
	if x != nil {
		return x.IncludeWarnings
	}
	return false
}

func (x *RequestOptions) GetAllowFallbackToCypher() bool {
	if x != nil {
		return x.AllowFallbackToCypher
	}
	return false
}

func (x *RequestOptions) GetStrictVariantDispatch() bool {
	if x != nil {
		return x.StrictVariantDispatch
	}
	return false
}

type ClientContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SdkLanguage     string                 `protobuf:"bytes,1,opt,name=sdk_language,json=sdkLanguage,proto3" json:"sdk_language,omitempty"`
	SdkVersion      string                 `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientContext) Reset() {
	*x = ClientContext{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientContext) ProtoMessage() {}

func (x *ClientContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientContext.ProtoReflect.Descriptor instead.
func (*ClientContext) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{4}
}

func (x *ClientContext) GetSdkLanguage() string {
	if x != nil {
		return x.SdkLanguage
	}
	return ""
}

func (x *ClientContext) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ClientContext) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Stats         *QueryStats            `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	Warnings      []*Diagnostic          `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResponse) GetStats() *QueryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *QueryResponse) GetWarnings() []*Diagnostic {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ExplainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExplainJson   []byte                 `protobuf:"bytes,1,opt,name=explain_json,json=explainJson,proto3" json:"explain_json,omitempty"`
	Stats         *QueryStats            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Warnings      []*Diagnostic          `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{6}
}

func (x *ExplainResponse) GetExplainJson() []byte {
	if x != nil {
		return x.ExplainJson
	}
	return nil
}

func (x *ExplainResponse) GetStats() *QueryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ExplainResponse) GetWarnings() []*Diagnostic {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type QueryStats struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	RowsReturned                 int64                  `protobuf:"varint,1,opt,name=rows_returned,json=rowsReturned,proto3" json:"rows_returned,omitempty"`
	DurationMs                   int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ConfiguredMaxWriteBatchBytes int64                  `protobuf:"varint,3,opt,name=configured_max_write_batch_bytes,json=configuredMaxWriteBatchBytes,proto3" json:"configured_max_write_batch_bytes,omitempty"`
	EffectiveMaxWriteBatchBytes  int64                  `protobuf:"varint,4,opt,name=effective_max_write_batch_bytes,json=effectiveMaxWriteBatchBytes,proto3" json:"effective_max_write_batch_bytes,omitempty"`
	MaxWriteBatchBytesTuned      bool                   `protobuf:"varint,5,opt,name=max_write_batch_bytes_tuned,json=maxWriteBatchBytesTuned,proto3" json:"max_write_batch_bytes_tuned,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *QueryStats) Reset() {
	*x = QueryStats{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStats) ProtoMessage() {}

func (x *QueryStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStats.ProtoReflect.Descriptor instead.
func (*QueryStats) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{7}
}

func (x *QueryStats) GetRowsReturned() int64 {
	if x != nil {
		return x.RowsReturned
	}
	return 0
}

func (x *QueryStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *QueryStats) GetConfiguredMaxWriteBatchBytes() int64 {
	if x != nil {
		return x.ConfiguredMaxWriteBatchBytes
	}
	return 0
}

func (x *QueryStats) GetEffectiveMaxWriteBatchBytes() int64 {
	if x != nil {
		return x.EffectiveMaxWriteBatchBytes
	}
	return 0
}

func (x *QueryStats) GetMaxWriteBatchBytesTuned() bool {
	if x != nil {
		return x.MaxWriteBatchBytesTuned
	}
	return false
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{8}
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{9}
}

type CapabilitiesResponse struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion                string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ParserVersions                 []string               `protobuf:"bytes,2,rep,name=parser_versions,json=parserVersions,proto3" json:"parser_versions,omitempty"`
	IrVersions                     []string               `protobuf:"bytes,3,rep,name=ir_versions,json=irVersions,proto3" json:"ir_versions,omitempty"`
	PreparedQuerySupported         bool                   `protobuf:"varint,4,opt,name=prepared_query_supported,json=preparedQuerySupported,proto3" json:"prepared_query_supported,omitempty"`
	ParameterBinding               string                 `protobuf:"bytes,5,opt,name=parameter_binding,json=parameterBinding,proto3" json:"parameter_binding,omitempty"`
	IndexDdlSupported              bool                   `protobuf:"varint,6,opt,name=index_ddl_supported,json=indexDdlSupported,proto3" json:"index_ddl_supported,omitempty"`
	MaxWriteBatchBytes             int64                  `protobuf:"varint,7,opt,name=max_write_batch_bytes,json=maxWriteBatchBytes,proto3" json:"max_write_batch_bytes,omitempty"`
	ConfiguredMaxWriteBatchBytes   int64                  `protobuf:"varint,8,opt,name=configured_max_write_batch_bytes,json=configuredMaxWriteBatchBytes,proto3" json:"configured_max_write_batch_bytes,omitempty"`
	EffectiveMaxWriteBatchBytes    int64                  `protobuf:"varint,9,opt,name=effective_max_write_batch_bytes,json=effectiveMaxWriteBatchBytes,proto3" json:"effective_max_write_batch_bytes,omitempty"`
	MaxWriteBatchBytesTuned        bool                   `protobuf:"varint,10,opt,name=max_write_batch_bytes_tuned,json=maxWriteBatchBytesTuned,proto3" json:"max_write_batch_bytes_tuned,omitempty"`
	StrictVariantDispatchSupported bool                   `protobuf:"varint,11,opt,name=strict_variant_dispatch_supported,json=strictVariantDispatchSupported,proto3" json:"strict_variant_dispatch_supported,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{10}
}

func (x *CapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetParserVersions() []string {
	if x != nil {
		return x.ParserVersions
	}
	return nil
}

func (x *CapabilitiesResponse) GetIrVersions() []string {
	if x != nil {
		return x.IrVersions
	}
	return nil
}

func (x *CapabilitiesResponse) GetPreparedQuerySupported() bool {
	if x != nil {
		return x.PreparedQuerySupported
	}
	return false
}

func (x *CapabilitiesResponse) GetParameterBinding() string {
	if x != nil {
		return x.ParameterBinding
	}
	return ""
}

func (x *CapabilitiesResponse) GetIndexDdlSupported() bool {
	if x != nil {
		return x.IndexDdlSupported
	}
	return false
}

func (x *CapabilitiesResponse) GetMaxWriteBatchBytes() int64 {
	if x != nil {
		return x.MaxWriteBatchBytes
	}
	return 0
}

func (x *CapabilitiesResponse) GetConfiguredMaxWriteBatchBytes() int64 {
	if x != nil {
		return x.ConfiguredMaxWriteBatchBytes
	}
	return 0
}

func (x *CapabilitiesResponse) GetEffectiveMaxWriteBatchBytes() int64 {
	if x != nil {
		return x.EffectiveMaxWriteBatchBytes
	}
	return 0
}

func (x *CapabilitiesResponse) GetMaxWriteBatchBytesTuned() bool {
	if x != nil {
		return x.MaxWriteBatchBytesTuned
	}
	return false
}

func (x *CapabilitiesResponse) GetStrictVariantDispatchSupported() bool {
	if x != nil {
		return x.StrictVariantDispatchSupported
	}
	return false
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*Value      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{11}
}

func (x *Row) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_BoolValue
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_StringValue
	//	*Value_BytesValue
	//	*Value_ListValue
	//	*Value_MapValue
	//	*Value_NullValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{12}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetMapValue() *MapValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

func (x *Value) GetNullValue() *NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_NullValue); ok {
			return x.NullValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,6,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,7,opt,name=map_value,json=mapValue,proto3,oneof"`
}

type Value_NullValue struct {
	NullValue *NullValue `protobuf:"bytes,8,opt,name=null_value,json=nullValue,proto3,oneof"`
}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_IntValue) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_BytesValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_MapValue) isValue_Kind() {}

func (*Value_NullValue) isValue_Kind() {}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{13}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*Value      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{14}
}

func (x *MapValue) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type NullValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullValue) Reset() {
	*x = NullValue{}
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullValue) ProtoMessage() {}

func (x *NullValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vitaledge_v1_dml_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullValue.ProtoReflect.Descriptor instead.
func (*NullValue) Descriptor() ([]byte, []int) {
	return file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP(), []int{15}
}

var File_api_proto_vitaledge_v1_dml_proto protoreflect.FileDescriptor

const file_api_proto_vitaledge_v1_dml_proto_rawDesc = "" +
	"\n" +
	" api/proto/vitaledge/v1/dml.proto\x12\fvitaledge.v1\"\xe3\x02\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12.\n" +
	"\x05input\x18\x02 \x01(\v2\x18.vitaledge.v1.QueryInputR\x05input\x126\n" +
	"\aoptions\x18\x03 \x01(\v2\x1c.vitaledge.v1.RequestOptionsR\aoptions\x123\n" +
	"\x06client\x18\x04 \x01(\v2\x1b.vitaledge.v1.ClientContextR\x06client\x12J\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2*.vitaledge.v1.QueryRequest.ParametersEntryR\n" +
	"parameters\x1aR\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.vitaledge.v1.ValueR\x05value:\x028\x01\"i\n" +
	"\n" +
	"QueryInput\x12\x18\n" +
	"\x06cypher\x18\x01 \x01(\tH\x00R\x06cypher\x129\n" +
	"\bprepared\x18\x02 \x01(\v2\x1b.vitaledge.v1.PreparedQueryH\x00R\bpreparedB\x06\n" +
	"\x04kind\"\xba\x01\n" +
	"\rPreparedQuery\x12%\n" +
	"\x0eparser_version\x18\x01 \x01(\tR\rparserVersion\x12\x1d\n" +
	"\n" +
	"ir_version\x18\x02 \x01(\tR\tirVersion\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12'\n" +
	"\x0ffallback_cypher\x18\x05 \x01(\tR\x0efallbackCypher\"\xee\x01\n" +
	"\x0eRequestOptions\x12\x1b\n" +
	"\tread_only\x18\x01 \x01(\bR\breadOnly\x12#\n" +
	"\rinclude_stats\x18\x02 \x01(\bR\fincludeStats\x12)\n" +
	"\x10include_warnings\x18\x03 \x01(\bR\x0fincludeWarnings\x127\n" +
	"\x18allow_fallback_to_cypher\x18\x04 \x01(\bR\x15allowFallbackToCypher\x126\n" +
	"\x17strict_variant_dispatch\x18\x05 \x01(\bR\x15strictVariantDispatch\"~\n" +
	"\rClientContext\x12!\n" +
	"\fsdk_language\x18\x01 \x01(\tR\vsdkLanguage\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\"\xb6\x01\n" +
	"\rQueryResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12%\n" +
	"\x04rows\x18\x02 \x03(\v2\x11.vitaledge.v1.RowR\x04rows\x12.\n" +
	"\x05stats\x18\x03 \x01(\v2\x18.vitaledge.v1.QueryStatsR\x05stats\x124\n" +
	"\bwarnings\x18\x04 \x03(\v2\x18.vitaledge.v1.DiagnosticR\bwarnings\"\x9a\x01\n" +
	"\x0fExplainResponse\x12!\n" +
	"\fexplain_json\x18\x01 \x01(\fR\vexplainJson\x12.\n" +
	"\x05stats\x18\x02 \x01(\v2\x18.vitaledge.v1.QueryStatsR\x05stats\x124\n" +
	"\bwarnings\x18\x03 \x03(\v2\x18.vitaledge.v1.DiagnosticR\bwarnings\"\x9e\x02\n" +
	"\n" +
	"QueryStats\x12#\n" +
	"\rrows_returned\x18\x01 \x01(\x03R\frowsReturned\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\x12F\n" +
	" configured_max_write_batch_bytes\x18\x03 \x01(\x03R\x1cconfiguredMaxWriteBatchBytes\x12D\n" +
	"\x1feffective_max_write_batch_bytes\x18\x04 \x01(\x03R\x1beffectiveMaxWriteBatchBytes\x12<\n" +
	"\x1bmax_write_batch_bytes_tuned\x18\x05 \x01(\bR\x17maxWriteBatchBytesTuned\":\n" +
	"\n" +
	"Diagnostic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13CapabilitiesRequest\"\xec\x04\n" +
	"\x14CapabilitiesResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12'\n" +
	"\x0fparser_versions\x18\x02 \x03(\tR\x0eparserVersions\x12\x1f\n" +
	"\vir_versions\x18\x03 \x03(\tR\n" +
	"irVersions\x128\n" +
	"\x18prepared_query_supported\x18\x04 \x01(\bR\x16preparedQuerySupported\x12+\n" +
	"\x11parameter_binding\x18\x05 \x01(\tR\x10parameterBinding\x12.\n" +
	"\x13index_ddl_supported\x18\x06 \x01(\bR\x11indexDdlSupported\x121\n" +
	"\x15max_write_batch_bytes\x18\a \x01(\x03R\x12maxWriteBatchBytes\x12F\n" +
	" configured_max_write_batch_bytes\x18\b \x01(\x03R\x1cconfiguredMaxWriteBatchBytes\x12D\n" +
	"\x1feffective_max_write_batch_bytes\x18\t \x01(\x03R\x1beffectiveMaxWriteBatchBytes\x12<\n" +
	"\x1bmax_write_batch_bytes_tuned\x18\n" +
	" \x01(\bR\x17maxWriteBatchBytesTuned\x12I\n" +
	"!strict_variant_dispatch_supported\x18\v \x01(\bR\x1estrictVariantDispatchSupported\"\x8c\x01\n" +
	"\x03Row\x125\n" +
	"\x06values\x18\x01 \x03(\v2\x1d.vitaledge.v1.Row.ValuesEntryR\x06values\x1aN\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.vitaledge.v1.ValueR\x05value:\x028\x01\"\xe7\x02\n" +
	"\x05Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x128\n" +
	"\n" +
	"list_value\x18\x06 \x01(\v2\x17.vitaledge.v1.ListValueH\x00R\tlistValue\x125\n" +
	"\tmap_value\x18\a \x01(\v2\x16.vitaledge.v1.MapValueH\x00R\bmapValue\x128\n" +
	"\n" +
	"null_value\x18\b \x01(\v2\x17.vitaledge.v1.NullValueH\x00R\tnullValueB\x06\n" +
	"\x04kind\"8\n" +
	"\tListValue\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.vitaledge.v1.ValueR\x06values\"\x96\x01\n" +
	"\bMapValue\x12:\n" +
	"\x06values\x18\x01 \x03(\v2\".vitaledge.v1.MapValue.ValuesEntryR\x06values\x1aN\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.vitaledge.v1.ValueR\x05value:\x028\x01\"\v\n" +
	"\tNullValue2\xf0\x01\n" +
	"\n" +
	"DmlService\x12B\n" +
	"\aExecute\x12\x1a.vitaledge.v1.QueryRequest\x1a\x1b.vitaledge.v1.QueryResponse\x12D\n" +
	"\aExplain\x12\x1a.vitaledge.v1.QueryRequest\x1a\x1d.vitaledge.v1.ExplainResponse\x12X\n" +
	"\x0fGetCapabilities\x12!.vitaledge.v1.CapabilitiesRequest\x1a\".vitaledge.v1.CapabilitiesResponseB;Z9github.com/spaceqraft/vitaledge/api/proto/vitaledge/v1;v1b\x06proto3"

var (
	file_api_proto_vitaledge_v1_dml_proto_rawDescOnce sync.Once
	file_api_proto_vitaledge_v1_dml_proto_rawDescData []byte
)

func file_api_proto_vitaledge_v1_dml_proto_rawDescGZIP() []byte {
	file_api_proto_vitaledge_v1_dml_proto_rawDescOnce.Do(func() {
		file_api_proto_vitaledge_v1_dml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_vitaledge_v1_dml_proto_rawDesc), len(file_api_proto_vitaledge_v1_dml_proto_rawDesc)))
	})
	return file_api_proto_vitaledge_v1_dml_proto_rawDescData
}

var file_api_proto_vitaledge_v1_dml_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_vitaledge_v1_dml_proto_goTypes = []any{
	(*QueryRequest)(nil),         // 0: vitaledge.v1.QueryRequest
	(*QueryInput)(nil),           // 1: vitaledge.v1.QueryInput
	(*PreparedQuery)(nil),        // 2: vitaledge.v1.PreparedQuery
	(*RequestOptions)(nil),       // 3: vitaledge.v1.RequestOptions
	(*ClientContext)(nil),        // 4: vitaledge.v1.ClientContext
	(*QueryResponse)(nil),        // 5: vitaledge.v1.QueryResponse
	(*ExplainResponse)(nil),      // 6: vitaledge.v1.ExplainResponse
	(*QueryStats)(nil),           // 7: vitaledge.v1.QueryStats
	(*Diagnostic)(nil),           // 8: vitaledge.v1.Diagnostic
	(*CapabilitiesRequest)(nil),  // 9: vitaledge.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 10: vitaledge.v1.CapabilitiesResponse
	(*Row)(nil),                  // 11: vitaledge.v1.Row
	(*Value)(nil),                // 12: vitaledge.v1.Value
	(*ListValue)(nil),            // 13: vitaledge.v1.ListValue
	(*MapValue)(nil),             // 14: vitaledge.v1.MapValue
	(*NullValue)(nil),            // 15: vitaledge.v1.NullValue
	nil,                          // 16: vitaledge.v1.QueryRequest.ParametersEntry
	nil,                          // 17: vitaledge.v1.Row.ValuesEntry
	nil,                          // 18: vitaledge.v1.MapValue.ValuesEntry
}
var file_api_proto_vitaledge_v1_dml_proto_depIdxs = []int32{
	1,  // 0: vitaledge.v1.QueryRequest.input:type_name -> vitaledge.v1.QueryInput
	3,  // 1: vitaledge.v1.QueryRequest.options:type_name -> vitaledge.v1.RequestOptions
	4,  // 2: vitaledge.v1.QueryRequest.client:type_name -> vitaledge.v1.ClientContext
	16, // 3: vitaledge.v1.QueryRequest.parameters:type_name -> vitaledge.v1.QueryRequest.ParametersEntry
	2,  // 4: vitaledge.v1.QueryInput.prepared:type_name -> vitaledge.v1.PreparedQuery
	11, // 5: vitaledge.v1.QueryResponse.rows:type_name -> vitaledge.v1.Row
	7,  // 6: vitaledge.v1.QueryResponse.stats:type_name -> vitaledge.v1.QueryStats
	8,  // 7: vitaledge.v1.QueryResponse.warnings:type_name -> vitaledge.v1.Diagnostic
	7,  // 8: vitaledge.v1.ExplainResponse.stats:type_name -> vitaledge.v1.QueryStats
	8,  // 9: vitaledge.v1.ExplainResponse.warnings:type_name -> vitaledge.v1.Diagnostic
	17, // 10: vitaledge.v1.Row.values:type_name -> vitaledge.v1.Row.ValuesEntry
	13, // 11: vitaledge.v1.Value.list_value:type_name -> vitaledge.v1.ListValue
	14, // 12: vitaledge.v1.Value.map_value:type_name -> vitaledge.v1.MapValue
	15, // 13: vitaledge.v1.Value.null_value:type_name -> vitaledge.v1.NullValue
	12, // 14: vitaledge.v1.ListValue.values:type_name -> vitaledge.v1.Value
	18, // 15: vitaledge.v1.MapValue.values:type_name -> vitaledge.v1.MapValue.ValuesEntry
	12, // 16: vitaledge.v1.QueryRequest.ParametersEntry.value:type_name -> vitaledge.v1.Value
	12, // 17: vitaledge.v1.Row.ValuesEntry.value:type_name -> vitaledge.v1.Value
	12, // 18: vitaledge.v1.MapValue.ValuesEntry.value:type_name -> vitaledge.v1.Value
	0,  // 19: vitaledge.v1.DmlService.Execute:input_type -> vitaledge.v1.QueryRequest
	0,  // 20: vitaledge.v1.DmlService.Explain:input_type -> vitaledge.v1.QueryRequest
	9,  // 21: vitaledge.v1.DmlService.GetCapabilities:input_type -> vitaledge.v1.CapabilitiesRequest
	5,  // 22: vitaledge.v1.DmlService.Execute:output_type -> vitaledge.v1.QueryResponse
	6,  // 23: vitaledge.v1.DmlService.Explain:output_type -> vitaledge.v1.ExplainResponse
	10, // 24: vitaledge.v1.DmlService.GetCapabilities:output_type -> vitaledge.v1.CapabilitiesResponse
	22, // [22:25] is the sub-list for method output_type
	19, // [19:22] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proto_vitaledge_v1_dml_proto_init() }
func file_api_proto_vitaledge_v1_dml_proto_init() {
	if File_api_proto_vitaledge_v1_dml_proto != nil {
		return
	}
	file_api_proto_vitaledge_v1_dml_proto_msgTypes[1].OneofWrappers = []any{
		(*QueryInput_Cypher)(nil),
		(*QueryInput_Prepared)(nil),
	}
	file_api_proto_vitaledge_v1_dml_proto_msgTypes[12].OneofWrappers = []any{
		(*Value_BoolValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_MapValue)(nil),
		(*Value_NullValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_vitaledge_v1_dml_proto_rawDesc), len(file_api_proto_vitaledge_v1_dml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_vitaledge_v1_dml_proto_goTypes,
		DependencyIndexes: file_api_proto_vitaledge_v1_dml_proto_depIdxs,
		MessageInfos:      file_api_proto_vitaledge_v1_dml_proto_msgTypes,
	}.Build()
	File_api_proto_vitaledge_v1_dml_proto = out.File
	file_api_proto_vitaledge_v1_dml_proto_goTypes = nil
	file_api_proto_vitaledge_v1_dml_proto_depIdxs = nil
}
