// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/vitaledge/v1/dml.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DmlService_Execute_FullMethodName         = "/vitaledge.v1.DmlService/Execute"
	DmlService_Explain_FullMethodName         = "/vitaledge.v1.DmlService/Explain"
	DmlService_GetCapabilities_FullMethodName = "/vitaledge.v1.DmlService/GetCapabilities"
)

// DmlServiceClient is the client API for DmlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DmlServiceClient interface {
	Execute(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Explain(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ExplainResponse, error)
	GetCapabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
}

type dmlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDmlServiceClient(cc grpc.ClientConnInterface) DmlServiceClient {
	return &dmlServiceClient{cc}
}

func (c *dmlServiceClient) Execute(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, DmlService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmlServiceClient) Explain(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainResponse)
	err := c.cc.Invoke(ctx, DmlService_Explain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmlServiceClient) GetCapabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, DmlService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DmlServiceServer is the server API for DmlService service.
// All implementations must embed UnimplementedDmlServiceServer
// for forward compatibility.
type DmlServiceServer interface {
	Execute(context.Context, *QueryRequest) (*QueryResponse, error)
	Explain(context.Context, *QueryRequest) (*ExplainResponse, error)
	GetCapabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	mustEmbedUnimplementedDmlServiceServer()
}

// UnimplementedDmlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDmlServiceServer struct{}

func (UnimplementedDmlServiceServer) Execute(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedDmlServiceServer) Explain(context.Context, *QueryRequest) (*ExplainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Explain not implemented")
}
func (UnimplementedDmlServiceServer) GetCapabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedDmlServiceServer) mustEmbedUnimplementedDmlServiceServer() {}
func (UnimplementedDmlServiceServer) testEmbeddedByValue()                    {}

// UnsafeDmlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DmlServiceServer will
// result in compilation errors.
type UnsafeDmlServiceServer interface {
	mustEmbedUnimplementedDmlServiceServer()
}

func RegisterDmlServiceServer(s grpc.ServiceRegistrar, srv DmlServiceServer) {
	// If the following call panics, it indicates UnimplementedDmlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DmlService_ServiceDesc, srv)
}

func _DmlService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmlServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DmlService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmlServiceServer).Execute(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DmlService_Explain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmlServiceServer).Explain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DmlService_Explain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmlServiceServer).Explain(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DmlService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmlServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DmlService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmlServiceServer).GetCapabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DmlService_ServiceDesc is the grpc.ServiceDesc for DmlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DmlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vitaledge.v1.DmlService",
	HandlerType: (*DmlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _DmlService_Execute_Handler,
		},
		{
			MethodName: "Explain",
			Handler:    _DmlService_Explain_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _DmlService_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/vitaledge/v1/dml.proto",
}
